models:
- name: efficientnet-b7
  launchers:
  - framework: dlsdk
    adapter: classification
  datasets:
  - name: imagenet_1000_classes
    reader: pillow_imread
    preprocessing:
    - type: rgb_to_bgr
    - type: resize
      size: 632
      aspect_ratio_scale: greater
      use_pillow: true
      interpolation: BICUBIC
    - type: crop
      use_pillow: true
      size: 600
    metrics:
    - name: accuracy@top1
      type: accuracy
      top_k: 1
    - name: accuracy@top5
      type: accuracy
      top_k: 5
