models:
  - name: inceptionv3-int8-sparse-60-onnx

    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        data_source: ImageNet
        annotation: imagenet1000.pickle
        reader: pillow_imread

        preprocessing:
        - type: resize
          size: 341
          aspect_ratio_scale: greater
          use_pillow: True
          interpolation: BILINEAR
        - type: crop
          size: 299
          use_pillow: True
        - type: bgr_to_rgb

        metrics:
          - name: accuracy@top1
            type: accuracy
            top_k: 1
          - name: accuracy@top5
            type: accuracy
            top_k: 5
