models:
  - name: mobilenetv2-ssdlite-v3-kitti
    launchers:
      - framework: dlsdk
        adapter:
          type: ssd_onnx
          bboxes_out: detected_boxes
          labels_out: detected_classes
          scores_out: detected_scores
    datasets:
      - name: KITTIDetection
        preprocessing:
          - type: resize
            size: 320

        postprocessing:
          - type: resize_prediction_boxes

        metrics:
        - type: map
          ignore_difficult: True
          presenter: print_scalar
