models:
  - name: openpose-pose-caffe

    launchers:
      - framework: dlsdk
        allow_reshape_input: True
        adapter: human_pose_estimation

    datasets:
      - name: ms_coco_keypoints

        preprocessing:
          - type: resize
            size: 368
            interpolation: CUBIC
            aspect_ratio_scale: width
          - type: padding
            stride: 8

        postprocessing:
          - type: filter
            apply_to: annotation
            area_range: 1, 10000000000
          - type: filter
            apply_to: prediction
            area_range: 1, 10000000000

        metrics:
          - name: AP
            type: coco_precision
            max_detections: 20

global_definitions: ../dataset_definitions.yml
