models:
  - name: resnet-50-cf
    launchers:
      - framework: caffe
        model:   resnet-50.prototxt
        weights: resnet-50.caffemodel
        adapter: classification
    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224
          - type: normalization
            mean: 104, 117, 123

  - name: resnet-50
    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: imagenet_1000_classes
        preprocessing:
          - type: resize
            size: 256
            aspect_ratio_scale: greater
          - type: crop
            size: 224
