models:
  - name: resnet-v2-50
    launchers:
      - framework: dlsdk
        adapter: classification
    datasets:
      - name: imagenet_1001_classes
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224
        metrics:
          - name: top1
            type: accuracy
            top_k: 1
          - name: top5
            type: accuracy
            top_k: 5
