models:
  - name: retinaface-mobilenetv2-0.25-modified
    launchers:
      - framework: dlsdk
        adapter:
          type: retinaface
          bboxes_outputs:
            - face_rpn_bbox_pred_stride32
            - face_rpn_bbox_pred_stride16
            - face_rpn_bbox_pred_stride8
          scores_outputs:
            - face_rpn_cls_prob_reshape_stride32
            - face_rpn_cls_prob_reshape_stride16
            - face_rpn_cls_prob_reshape_stride8
          landmarks_outputs:
            - face_rpn_landmark_pred_stride32
            - face_rpn_landmark_pred_stride16
            - face_rpn_landmark_pred_stride8
    datasets:
      - name: wider
        preprocessing:
          - type: resize
            size: 640
        postprocessing:
          - type: cast_to_int
          - type: clip_boxes
            size: 1024
            apply_to: annotation
          - type: filter
            apply_to: annotation
            height_range: 64, 1024
            is_empty: True

        metrics:
          - type: map
            ignore_difficult: True
            include_boundaries: False
            allow_multiple_matches_per_ignored: False
            distinct_conf: False
      - name: vgg2face
        data_source: VGGFaces2/test
        annotation: vggfaces2_1000.pickle
        subsample_size: 1000
        preprocessing:
          - type: resize
            size: 640
        metrics:
          - type: per_point_normed_error
            presenter: print_vector
          - type: normed_error


global_definitions: ../dataset_definitions.yml
