models:
  - name: se-resnext-50
    launchers:
      - framework: dlsdk
        adapter: classification

    datasets:
      - name: imagenet_1000_classes_2015
        preprocessing:
          - type: resize
            size: 256
          - type: crop
            size: 224
