models:
  - name:  ssd_mobilenet_v2_quantized
    launchers:
      - framework: dlsdk
        adapter: ssd

    datasets:
      - name: ms_coco_detection_91_classes

        preprocessing:
          - type: resize
            size: 300
        postprocessing:
          - type: resize_prediction_boxes
        metrics:
          - type: coco_precision
            max_detections: 100

global_definitions: ../dataset_definitions.yml
