models:
  - name:  ssd_mobilenet_v2
    launchers:
      - framework: dlsdk
        adapter: ssd

    datasets:
      - name: ms_coco_detection_91_classes
        preprocessing:
          - type: resize
            dst_width: 256
            dst_height: 256
        postprocessing:
          - type: resize_prediction_boxes
        metrics:
          - type: coco_precision

global_definitions: ../dataset_definitions.yml
