models:
  - name: two-stage-product-reco
    launchers:
      - framework: dlsdk
        adapter:
          type: two_stage_detection
          boxes_out: rpn_bbox
          cls_out: cls_probs
    datasets:
      - name: ProductDetection

        preprocessing:
          - type: resize
            size: 512

        postprocessing:
          - type: resize_prediction_boxes
        metrics:
        - type: map
