models:
  - name: vas-face-detection-stage2
    launchers:
    - framework: dlsdk
      allow_reshape_input: true
      adapter:
        type: face_detection_refinement
        threshold: 0.5
    datasets:
    - name: youtube-faces
      data_source: YTF/frame_images_DB
      reader: opencv_imread
      annotation_conversion:
          converter: youtube_faces_face_detection
          annotation_dir: YTF/frame_images_DB
          image_dir: YTF/frame_images_DB
          annotation_nums: 200
          stage1_detected_faces_file: vas_pickle/fd_stage1_candidates.pickle
      preprocessing:
      #- type: face_patch
      - type: candidate_crop #after https://github.com/opencv/open_model_zoo/pull/1278
        scale_width: 1.5
        scale_height: 1.5
      - type: resize
        dst_width: 48
        dst_height: 48
        interpolation: linear
      metrics:
      - type: youtube_faces_accuracy
        overlap: 0.4
        relative_size: 0.25
        presenter: print_scalar
