models:
  - name: vas-face-detection-stage1
    launchers:
    - framework: dlsdk
      allow_reshape_input: true
      adapter:
        type: face_detection
        score_threshold: 0.35
        layer_names: ['b12', 'b16', 'b24', 'b32', 'b48', 'b64', 'b96', 'b128', 'b192']
        anchor_sizes: [4, 3, 2, 3, 2, 3, 2, 3, 2]
        window_scales: [8, 8, 8, 16, 16, 32, 32, 64, 64]
        window_lengths: [12, 16, 24, 32, 48, 64, 96, 128, 192]
    datasets:
    - name: youtube-faces
      data_source: YTF/frame_images_DB
      reader: opencv_imread
      annotation_conversion:
          converter: youtube_faces_face_detection
          annotation_dir: YTF/frame_images_DB
          image_dir: YTF/frame_images_DB
          annotation_nums: 200
      preprocessing:
        - type: face_detection_image_pyramid
          min_face_ratio: 0.05
          resize_scale: 2
      postprocessing:
        - type: nms
          include_boundaries: false
          use_min_area: true
          overlap: 0.66
      metrics:
        - type: youtube_faces_accuracy
          overlap: 0.4
          relative_size: 0.25
          presenter: print_scalar
