models:
  - name: yolo_v3_tiny
    launchers:
      - framework: dlsdk
        adapter:
          type: yolo_v3_onnx
          boxes_out: yolonms_layer_1
          scores_out: yolonms_layer_1:1
          indices_out: yolonms_layer_1:2
        inputs:
          - name: image_shape
            type: ORIG_IMAGE_INFO
    datasets:
      - name: ms_coco_detection_80_class_without_background
        reader: pillow_imread
        preprocessing:
          - type: resize
            size: 416
            interpolation: BICUBIC
            use_pillow: True
            aspect_ratio_scale: fit_to_window
          - type: padding
            pad_value: 128, 128, 128
            size: 416
        metrics:
          - type: map
            integral: 11point
            ignore_difficult: true
            presenter: print_scalar
          - type: coco_precision
            max_detections: 100
            threshold: 0.5
